### ISSUE TITLE
Add GithubAction to comile JOSS paper draft

### ISSUE THREAD

**Issue by ckittl** [ie3-institute/OSMoGrid#63]
`.github/workflows/draft-pdf.yml`:

```yaml
on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: publication/joss_introduction.md
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: paper
          # This is the output path where Pandoc will write the compiled
          # PDF. Note, this should be the same directory as the input
          # paper.md
          path: publication/joss_introduction.pdf
```
